#!/usr/bin/node 

// either install in /usr/local/wekan/bin/wekan-mail
// or fix the exim4 transport config to point to this script


const fs = require('fs');
const util = require('util');
const simpleParser = require('mailparser').simpleParser;

var uid = Math.random().toString(36).replace(/[^a-z]+/g, '');

simpleParser(process.stdin, {}, (err, parsed) => {
  if (err) {
     // if a exim4 pipe transport outputs something, where does it go?
    console.log('wekan-email error', err);
  } else {
    fs.writeFileSync('/tmp/'+uid+'.mail', util.format(process.argv, process.env, parsed));
  }
});


/*
var content = '';
process.stdin.resume();
process.stdin.on('data', function(buf) { content += buf.toString(); });
process.stdin.on('end', function() {
  // your code here
  fs.writeFileSync('/tmp/'+uid, util.format(process.argv, process.env, content));
//                   console.log(content.split('').reverse().join(''));
});

*/


/* Local Variables:  */
/* mode: javascript  */
/* End:              */
